---
- name: Install required debian packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items: 
    - curl
    - git

- name: Creating directories
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/node_exporter/textfile_collector

- name: Install L2TP collector
  template:
    src: freifunk-prometheus-l2tp.bash.j2
    dest: /usr/local/bin/freifunk-prometheus-l2tp.bash
    mode: 0755

- name: Ensure that cronjob for L2TP collector exists
  cron:
   name: "Prometheus L2TP Collector" 
   user: root
   cron_file: node_exporter
   minute: "*/2" 
   job: "/usr/local/bin/freifunk-prometheus-l2tp.bash > /dev/null"


- name: Install dnsmasq collector
  template:
    src: freifunk-prometheus-dnsmasq.bash.j2
    dest: /usr/local/bin/freifunk-prometheus-dnsmasq.bash
    mode: 0755

- name: Ensure that cronjob for dnsmasq collector exists
  cron:
   name: "Prometheus dnsmasq Collector" 
   user: root
   cron_file: node_exporter
   minute: "*/2" 
   job: "/usr/local/bin/freifunk-prometheus-dnsmasq.bash > /dev/null"

- name: Install dnsmasq leasaes collector
  template:
    src: freifunk-prometheus-dnsmasq-leases.bash.j2
    dest: /usr/local/bin/freifunk-prometheus-dnsmasq-leases.bash
    mode: 0755

- name: Ensure that cronjob for dnsmasq leases collector exists
  cron:
   name: "Prometheus dnsmasq leases Collector" 
   user: root
   cron_file: node_exporter
   job: "/usr/local/bin/freifunk-prometheus-dnsmasq-leases.bash > /dev/null"

- name: Install fastd collector
  template:
    src: freifunk-prometheus-fastd.bash.j2
    dest: /usr/local/bin/freifunk-prometheus-fastd.bash
    mode: 0755

- name: Ensure that cronjob for fastd collector exists
  cron:
   name: "Prometheus fastd Collector" 
   user: root
   cron_file: node_exporter
   minute: "*/2" 
   job: "/usr/local/bin/freifunk-prometheus-fastd.bash > /dev/null"

- name: Set node_exporter variables
  vars:
    node_exporter_version: "0.12.0"
  set_fact:
    node_exporter_version: "{{ node_exporter_version }}"
    node_exporter_basename: "node_exporter-{{ node_exporter_version }}.linux-amd64"

- name: Download node_exporter binary from github
  vars:
    node_exporter_dlpath: "https://github.com/prometheus/node_exporter/releases/download/{{ node_exporter_version }}/{{ node_exporter_basename }}.tar.gz"
  unarchive:
    src: "{{ node_exporter_dlpath }}"
    dest: /srv/
    owner: root
    group: root
    copy: no

- name: create canonical node_exporter symlink
  file:
    src: "{{ node_exporter_basename }}"
    dest: /srv/node_exporter 
    owner: root
    group: root
    state: link

- name: Create systemd service files
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  notify:
    - Restart node_exporter

- name: Enable and start Prometheus node exporter
  service:
    name: node_exporter
    enabled: true
    state: started
