---
#- name: Add pgp_key for batman-adv repository
#  apt_key: keyserver="pool.sks-keyservers.net" id="{{ batman_adv.repository.pgp_key }}"

- name: Add repository for batman-adv
  apt_repository: repo="deb {{ batman_adv.repository.url }}"

- name: Install batman-adv dependencies
  apt: name="{{ item }}"
  with_items:
    - lsof
    - linux-headers-amd64
    - batman-adv-dkms

- name: Copy kernel postinst downgrade hook
  copy: >
    src=dkms-batman-adv-downgrade
    dest=/etc/kernel/postinst.d/dkms-batman-adv-downgrade
    mode=0755

- name: Ensure correct version was installed
  shell: /etc/kernel/postinst.d/dkms-batman-adv-downgrade $(uname -r)
  register: batman_adv_version_result
  changed_when: "'already installed' not in batman_adv_version_result.stderr"

- name: Enable batman during boot
  lineinfile: dest=/etc/modules line=batman-adv

- name: Load batman-adv module
  modprobe: name=batman-adv

- name: Create batman systemd script
  template:
    src: freifunk-mesh.service.j2
    dest: /etc/systemd/system/freifunk-mesh-{{ item.name }}.service
    mode: 0644
  with_items: batman.instances

- name: Enable batman systemd scripts
  service: name=freifunk-mesh-{{ item.name }} enabled=yes state=started
  with_items: batman.instances

- name: Create batman script
  template:
    src: freifunk-mesh.j2
    dest: /usr/local/bin/freifunk-mesh-{{ item.name }}
    mode: 0755
  with_items: batman.instances

