---
- name: Install basic tools
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - apt-transport-https
    - dnsutils
    - mtr
    - vim
    - htop
    - bwm-ng
    - screen
    - tmux
    - curl
    - haveged
    - figlet

- name: figlet name
  command: /usr/bin/figlet -c -w 80 ${ansible_hostname}
  register: figlethost

- name: deploy motd file
  template: src=motd.j2 dest=/etc/motd owner=root mode=0644

- name: Set sysctl kernel.panic_on_oops to 1
  sysctl: name=kernel.panic_on_oops value=1 state=present reload=yes

- name: Set sysctl kernel.panic to 1
  sysctl: name=kernel.panic value=1 state=present reload=yes

- name: Remove user freifunk
  user: name=freifunk state=absent remove=yes

- name: Remove home directory of user freifunk
  file: path=/home/freifunk state=absent

- name: Install sudo
  apt: name=sudo

- name: Craete users and add to sudo group
  user: name={{ item }} groups=sudo
  with_items: "{{ administrators }}"

- name: Set up authorized_keys for root
  authorized_key: user=root key="{{ lookup('file', "keyfiles/" + item + '.pub') }}" state=present
  with_items: "{{ administrators }}"

