---
- name: Install isc-dhcp-server package
  apt: pkg=isc-dhcp-server update_cache=yes cache_valid_time=3600

- name: Copy isc-dhcp6-server init script
  copy: 
     src: isc-dhcp6-server.init
     dest: /etc/init.d/isc-dhcp6-server
     mode: 0755

- name: Create dhcpd.conf in /etc/dhcp/dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644

- name: Create dhcpd6.conf in /etc/dhcp/dhcpd6.conf
  template: 
     src: dhcpd6.conf.j2
     dest: /etc/dhcp/dhcpd6.conf 
     mode: 0644

- name: Copy isc-dhcp6-server to /etc/default/isc-dhcp6-server
  copy: 
     src: isc-dhcp6-server.default
     dest: /etc/default/isc-dhcp6-server
     mode: 0644

- name: Create dhcpd6.leases file
  file: 
     path: /var/lib/dhcp/dhcpd6.leases
     mode: 0644
     owner: root
     group: root
     state: touch

- name: Configure /etc/default/isc-dhcp-server
  lineinfile: dest=/etc/default/isc-dhcp-server regexp="^INTERFACES=" line='INTERFACES="br0-niers"'

- name: Configure /etc/default/isc-dhcp6-server
  lineinfile: dest=/etc/default/isc-dhcp6-server regexp="^INTERFACES=" line='INTERFACES="br0-niers"'

- name: Restart isc-dhcp-server
  service: name=isc-dhcp-server enabled=true state=restarted

- name: Restart isc-dhcp6-server
  service: name=isc-dhcp6-server enabled=true state=restarted
