---
- name: Copy template timesyncd.conf to /etc/systemd/timesyncd.conf
  template:
      src: timesyncd.conf.j2
      dest: /etc/systemd/timesyncd.conf
      mode: 0644
  notify:
    - Restart systemd-timesyncd

- name: Restart service systemd-timesyncd
  service: 
      name: systemd-timesyncd 
      enabled: true 
      state: started
